export const FETCHING_POKIMONS = "FETCHING_POKIMONS";
export const FETCHING_POKIMONS_SUCCESS = "FETCHING_POKIMONS_SUCCESS ";
export const FETCHING_POKIMONS_FAIL = "FETCHING_POKIMONS_FAIL";

export const FETCHING_POKIMON_DETAILS = "FETCHING_POKIMON_DETAILS";
export const FETCHING_POKIMON_DETAILS_SUCCESS =
  "FETCHING_POKIMON_DETAILS_SUCCESS ";
export const FETCHING_POKIMON_DETAILS_FAIL = "FETCHING_POKIMON_DETAILS_FAIL";
